export const DEFAULT_ENV = {
  PORT: 3000,
  NODE_ENV: 'development',
  ORDER_LOCK_SWEEP_MS: 30_000,
  REQUEST_TIMEOUT_MS: 35_000,
  ROUTE_OPERATION_TIMEOUT_MS: 12_000,
  GLOBAL_RATE_LIMIT: 1000,
  AUTH_RATE_LIMIT: 100,
  MAX_CONCURRENT_REQUESTS: 300,
  DATABASE_CONNECTION_LIMIT: 5,
  DATABASE_POOL_TIMEOUT: 10,
  ENABLE_WS: true,
  APP_BASE_URL: 'https://neocash.online',
  ADMIN_PANEL_API_BASE_URL: 'http://localhost:3000',
  CORS_ORIGINS: [
    'http://localhost:5173',
    'http://localhost:4173',
    'http://localhost',
    'https://localhost',
    'capacitor://localhost',
    'ionic://localhost',
    'app://localhost',
    'https://neocash.online',
    'https://www.neocash.online',
  ],
  ADMIN_PANEL_ORIGINS: [
    'http://localhost:3000',
    'http://localhost:5174',
  ],
} as const;
